### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by kli0rf** [vitalyvb/iptv2rtsp-proxy#1]
Is there a way to disable logging completely? It kills the whole armbian on Odroid, running from micro sd card, and i suspect, this happens because of the message flood on daemon.log.

**Comment by vitalyvb** [comment]
Hi,

a few options:

1) Often, syslog daemons have some ability to filter messages, depending on what's Odroid is using, it may be possible to drop messages from "iptv2rtsp-proxy", or filter some frequent messages.

2) "-f" option will run iptv2rtsp-proxy in foreground, i.e. it will not fork by itself, and all logging message will be sent to stderr instead, and it's easy to drop it: 
```bash
iptv2rtsp-proxy -f > /dev/null 2>&1 < /dev/null &
```
or something similar, depending on how you start it.

3) Change source code - comment out "syslog(level, "%s", buf);" in "server.c", i.e. change 
```c
    if (!log_to_stderr){
        syslog(level, "%s", buf);
    } else {
```
to 
```c
    if (!log_to_stderr){
//        syslog(level, "%s", buf);
    } else {

```

Hope this helps

**Comment by kli0rf** [comment]
Thanks for incredibly quick response, the option 3 seems to be an option i was looking for!
